FROM dotnet-31-rhel7:latest
# This image provides a .NET Core 2.1 environment you can use to run your .NET
# applications.

USER 0

# Install Java JDK 8
RUN yum -y install jenkins java-1.8.0-openjdk

USER 1001

env PATH "$PATH:/usr/lib/sonar-scanner/" 
